spring:
  profiles:
    active: @activatedProperties@ # 这里引用的是pom.xml中配置的key，@activatedProperties@ 中内如必须与 profile=>properties=> activatedProperties节点一致
  jackson:
    # 统一转换日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    hikari:
      connection-timeout: 300000
      validation-timeout: 3000
      idle-timeout: 120000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath*:mappers/*.xml
