server:
  port: 8888
  servlet:
    context-path: /springboot-service
spring:
  application:
    name: springfox-swagger
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB #将之前的6M改成了100M
      max-request-size: 100MB #将之前的6M改成了100M
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.44.70:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
#logging:
logging:
  level:
    com.example: DEBUG
  file:
    path:  ./log/
#  config: classpath:logback-spring.xml.bak
minio:
  # 地址 应该使用api的端口，即使用--address指定的端口
  endpoint: http://101.35.44.70:9000
  # 账号
  accessKey: admin
  # 密码
  secretKey: admin123456
  # 默认存储桶
  bucket:
    # 文件存储桶
    bucketName: file
    # 分片存储桶
    chunk: chunk
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}