server:
  port: 8888
  servlet:
    context-path: /springboot-service
spring:
  profiles:
    active: @activatedProperties@ # 这里引用的是pom.xml中配置的key，@activatedProperties@ 中内如必须与 profile=>properties=> activatedProperties节点一致
  jackson:
    # 统一转换日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB #将之前的6M改成了100M
      max-request-size: 100MB #将之前的6M改成了100M
  mvc:
    pathmatch:
      # Springfox3使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.44.70:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
mybatis:
  config-location: classpath:sqlMapConfig.xml
  mapper-locations: classpath:mappers/*.xml
#logging:
logging:
  level:
    com.example: DEBUG
  file:
    path:  ./log/
#  config: classpath:logback-spring.xml.bak
minio:
  # 地址 应该使用api的端口，即使用--address指定的端口
  endpoint: http://101.35.44.70:9000
  # 账号
  accessKey: admin
  # 密码
  secretKey: admin123456
knife4j:
  enable: false
  production: true
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    language: zh-CN
    enableSwaggerModels: true
    swaggerModelName: 实体类列表
    enableDocumentManage: true
    enableReloadCacheParameter: true
    enableVersion: true
  documents:
    locations: classpath:markdowns/*